# name: 0001 Github Actions
# run-name: ${{ github.actor }} is running GitHub Actions 🚀

on: push

jobs:
  setup:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: ls -la